name: Prettier

on:
  pull_request:
    paths:
      - '*.js'
      - '*.html'
      - '*.json'
      - '*.md'
      - '*.yml'
      - '*.css'
      - '*.scss'
      - '**/*.js'
      - '**/*.html'
      - '**/*.json'
      - '**/*.md'
      - '**/*.yml'
      - '**/*.css'
      - '**/*.scss'

permissions:
  contents: write

jobs:
  Prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write {**/*,*}.{js,html,json,md,yml,css,scss}"
          branch: "${{ github.head_ref }}"
          file_pattern: "."
          only_changed: True
          github_token: ${{ secrets.GITHUB_TOKEN }}
